// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfR4TI94ALjOFRXXiKro3gdnP2zZnZpgA',
    appId: '1:346371131827:web:b8c5f4791ba58ae62823c6',
    messagingSenderId: '346371131827',
    projectId: 'stockly-project',
    authDomain: 'stockly-project.firebaseapp.com',
    storageBucket: 'stockly-project.firebasestorage.app',
    measurementId: 'G-RTWN724739',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwHe9tcWALZ6uQBak8ii78CskpEEwk2rc',
    appId: '1:346371131827:android:3513d522e090feb52823c6',
    messagingSenderId: '346371131827',
    projectId: 'stockly-project',
    storageBucket: 'stockly-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApxTcI3tXewMx8CH2xxBJR1hpK6XgGFD0',
    appId: '1:346371131827:ios:73c5a305860420332823c6',
    messagingSenderId: '346371131827',
    projectId: 'stockly-project',
    storageBucket: 'stockly-project.firebasestorage.app',
    iosBundleId: 'com.example.stocklyProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApxTcI3tXewMx8CH2xxBJR1hpK6XgGFD0',
    appId: '1:346371131827:ios:73c5a305860420332823c6',
    messagingSenderId: '346371131827',
    projectId: 'stockly-project',
    storageBucket: 'stockly-project.firebasestorage.app',
    iosBundleId: 'com.example.stocklyProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfR4TI94ALjOFRXXiKro3gdnP2zZnZpgA',
    appId: '1:346371131827:web:b8935061ba3297f42823c6',
    messagingSenderId: '346371131827',
    projectId: 'stockly-project',
    authDomain: 'stockly-project.firebaseapp.com',
    storageBucket: 'stockly-project.firebasestorage.app',
    measurementId: 'G-HML1BVFP1D',
  );
}
